import { BadgeCheck, Code, Leaf, Activity, HeartPulse, Layers, Briefcase, CpuChip, Palette, GraduationCap, Database, ShieldCheck, Wifi, Car, Cpu, Atom, Lightbulb, Building } from 'lucide-react';
import { IconType } from 'react-icons';

export interface CourseOption {
  value: string;
  label: string;
  category: string;
  fees: string;
  duration: string;
  scholarshipFees?: string;
}

export interface DetailedCourse {
  id: number;
  name: string;
  category: string;
  icon: any; // This will be a Lucide icon reference
  description: string;
  duration: string;
  averageFees: string;
  scholarshipFees: string;
  topUniversities: string[];
  careerProspects: string[];
  eligibility: string;
  skills: string[];
  featured: boolean;
}

// Course categories for filtering
export const courseCategories = [
  { value: 'all', label: 'All Categories' },
  { value: 'engineering', label: 'Engineering & Technology' },
  { value: 'medical', label: 'Medical & Health Sciences' },
  { value: 'business', label: 'Business & Management' },
  { value: 'arts', label: 'Arts & Humanities' },
  { value: 'science', label: 'Science' },
  { value: 'design', label: 'Design & Media' },
];

// Course options for dropdown select
export const courseOptions: CourseOption[] = [
  { value: 'btech_cse', label: 'B.Tech Computer Science & Engineering', category: 'engineering', fees: '$3000/year', duration: '4 years', scholarshipFees: '$1000/semester' },
  { value: 'btech_cyber', label: 'B.Tech Cyber Security', category: 'engineering', fees: '$3000/year', duration: '4 years', scholarshipFees: '$1200/semester' },
  { value: 'btech_ai', label: 'B.Tech Artificial Intelligence', category: 'engineering', fees: '$3000/year', duration: '4 years', scholarshipFees: '$1200/semester' },
  { value: 'btech_mechanical', label: 'B.Tech Mechanical Engineering', category: 'engineering', fees: '$3000/year', duration: '4 years', scholarshipFees: '$900/semester' },
  { value: 'btech_civil', label: 'B.Tech Civil Engineering', category: 'engineering', fees: '$3000/year', duration: '4 years', scholarshipFees: '$900/semester' },
  { value: 'btech_electrical', label: 'B.Tech Electrical Engineering', category: 'engineering', fees: '$3000/year', duration: '4 years', scholarshipFees: '$750/semester' },
  { value: 'btech_electronics', label: 'B.Tech Electronics & Communication Engineering', category: 'engineering', fees: '$3000/year', duration: '4 years', scholarshipFees: '$900/semester' },
  { value: 'btech_iot', label: 'B.Tech Internet of Things (IoT)', category: 'engineering', fees: '$3000/year', duration: '4 years', scholarshipFees: '$1200/semester' },
  { value: 'btech_auto', label: 'B.Tech Automobile Engineering', category: 'engineering', fees: '$3000/year', duration: '4 years', scholarshipFees: '$900/semester' },
  { value: 'btech_biomedical', label: 'B.Tech Biomedical Engineering', category: 'engineering', fees: '$3000/year', duration: '4 years', scholarshipFees: '$1200/semester' },
  { value: 'btech_ev', label: 'B.Tech Electric Vehicle Technology', category: 'engineering', fees: '$3000/year', duration: '4 years', scholarshipFees: '$1200/semester' },
  { value: 'btech_drone', label: 'B.Tech Drone Technology', category: 'engineering', fees: '$3000/year', duration: '4 years', scholarshipFees: '$1200/semester' },
  { value: 'btech_mechatronics', label: 'B.Tech Mechatronics Engineering', category: 'engineering', fees: '$3000/year', duration: '4 years', scholarshipFees: '$900/semester' },
  { value: 'btech_aerospace', label: 'B.Tech Aerospace Engineering', category: 'engineering', fees: '$4000/year', duration: '4 years', scholarshipFees: '$1200/semester' },
  
  { value: 'mtech_cse', label: 'M.Tech Computer Science & Engineering', category: 'engineering', fees: '$4000/year', duration: '2 years', scholarshipFees: '$1250/semester' },
  { value: 'mtech_mechanical', label: 'M.Tech Mechanical Engineering', category: 'engineering', fees: '$4000/year', duration: '2 years', scholarshipFees: '$1250/semester' },
  { value: 'mtech_civil', label: 'M.Tech Civil Engineering', category: 'engineering', fees: '$4000/year', duration: '2 years', scholarshipFees: '$1250/semester' },
  { value: 'mtech_ai', label: 'M.Tech Artificial Intelligence', category: 'engineering', fees: '$4000/year', duration: '2 years', scholarshipFees: '$1250/semester' },
  { value: 'mtech_data', label: 'M.Tech Data Science', category: 'engineering', fees: '$4000/year', duration: '2 years', scholarshipFees: '$1250/semester' },
  { value: 'mtech_cyber', label: 'M.Tech Cyber Security', category: 'engineering', fees: '$4000/year', duration: '2 years', scholarshipFees: '$1250/semester' },
  { value: 'mtech_iot', label: 'M.Tech Internet of Things (IoT)', category: 'engineering', fees: '$4000/year', duration: '2 years', scholarshipFees: '$1250/semester' },
  { value: 'mtech_renewable', label: 'M.Tech Renewable Energy Resources', category: 'engineering', fees: '$4000/year', duration: '2 years', scholarshipFees: '$1250/semester' },
  { value: 'mtech_environmental', label: 'M.Tech Environmental Engineering', category: 'engineering', fees: '$4000/year', duration: '2 years', scholarshipFees: '$1250/semester' },
  
  { value: 'diploma_cse', label: 'Diploma in Computer Science & Engineering', category: 'engineering', fees: '$3000/year', duration: '3 years', scholarshipFees: '$800/semester' },
  { value: 'diploma_mechanical', label: 'Diploma in Mechanical Engineering', category: 'engineering', fees: '$3000/year', duration: '3 years', scholarshipFees: '$800/semester' },
  { value: 'diploma_electronics', label: 'Diploma in Electronics & Communication Engineering', category: 'engineering', fees: '$3000/year', duration: '3 years', scholarshipFees: '$800/semester' },
  { value: 'diploma_automobile', label: 'Diploma in Automobile Engineering', category: 'engineering', fees: '$3000/year', duration: '3 years', scholarshipFees: '$800/semester' },
  { value: 'diploma_electrical', label: 'Diploma in Electrical Engineering', category: 'engineering', fees: '$3000/year', duration: '3 years', scholarshipFees: '$800/semester' },
  { value: 'diploma_civil', label: 'Diploma in Civil Engineering', category: 'engineering', fees: '$3000/year', duration: '3 years', scholarshipFees: '$800/semester' },
  
  { value: 'bsc_animation', label: 'BSc Animation VFX and Game Art', category: 'design', fees: '$5000/year', duration: '3 years', scholarshipFees: '$1200/semester' },
  { value: 'bsc_design', label: 'BSc Design', category: 'design', fees: '$5000/year', duration: '4 years', scholarshipFees: '$1200/semester' },
  
  { value: 'bpharm', label: 'B.Pharmacy', category: 'medical', fees: '$4000/year', duration: '4 years', scholarshipFees: '$1250/semester' },
  { value: 'bpharm_practice', label: 'B.Pharmacy (Practice)', category: 'medical', fees: '$4000/year', duration: '4 years', scholarshipFees: '$1250/semester' },
  { value: 'bpharm_lateral', label: 'B.Pharmacy (Lateral Entry)', category: 'medical', fees: '$4000/year', duration: '3 years', scholarshipFees: '$1250/semester' },
  { value: 'dpharm', label: 'D.Pharmacy', category: 'medical', fees: '$4000/year', duration: '2 years', scholarshipFees: '$1250/semester' },
  
  { value: 'mpharm_pharmaceutics', label: 'M.Pharmacy - Pharmaceutics', category: 'medical', fees: '$4000/year', duration: '2 years', scholarshipFees: '$1500/semester' },
  { value: 'mpharm_pharmacology', label: 'M.Pharmacy - Pharmacology', category: 'medical', fees: '$4000/year', duration: '2 years', scholarshipFees: '$1500/semester' },
  { value: 'msc_pharmacovigilance', label: 'M.Sc. Pharmacovigilance', category: 'medical', fees: '$4000/year', duration: '2 years', scholarshipFees: '$1500/semester' },
  { value: 'msc_clinical', label: 'M.Sc. Clinical Research', category: 'medical', fees: '$4000/year', duration: '2 years', scholarshipFees: '$1000/semester' },
  
  { value: 'mba', label: 'MBA (Master of Business Administration)', category: 'business', fees: '$3200/year', duration: '2 years', scholarshipFees: '$1000/semester' },
  { value: 'mba_marketing', label: 'MBA in Marketing', category: 'business', fees: '$3200/year', duration: '2 years', scholarshipFees: '$1000/semester' },
  { value: 'mba_finance', label: 'MBA in Finance', category: 'business', fees: '$3200/year', duration: '2 years', scholarshipFees: '$1000/semester' },
  { value: 'mba_hr', label: 'MBA in Human Resource', category: 'business', fees: '$3200/year', duration: '2 years', scholarshipFees: '$1000/semester' },
  { value: 'mba_it', label: 'MBA in IT', category: 'business', fees: '$3200/year', duration: '2 years', scholarshipFees: '$1000/semester' },
  { value: 'mba_digital', label: 'MBA in Digital Marketing', category: 'business', fees: '$3200/year', duration: '2 years', scholarshipFees: '$1000/semester' },
  { value: 'mba_logistics', label: 'MBA in Logistics & Supply Chain Management', category: 'business', fees: '$5000/year', duration: '2 years', scholarshipFees: '$1500/semester' },
  { value: 'mba_event', label: 'MBA in Event Management', category: 'business', fees: '$3200/year', duration: '2 years', scholarshipFees: '$1000/semester' },
  { value: 'mba_media', label: 'MBA in Media Studies', category: 'business', fees: '$3200/year', duration: '2 years', scholarshipFees: '$1000/semester' },
  { value: 'mba_sales', label: 'MBA in Sales and Distribution Management', category: 'business', fees: '$3200/year', duration: '2 years', scholarshipFees: '$1000/semester' },
  { value: 'mba_retail', label: 'MBA in Retail Management', category: 'business', fees: '$5000/year', duration: '2 years', scholarshipFees: '$1500/semester' },
  { value: 'mba_financial', label: 'MBA in Financial Analytics', category: 'business', fees: '$5000/year', duration: '2 years', scholarshipFees: '$1500/semester' },
  { value: 'mba_exec', label: 'MBA - Executive', category: 'business', fees: '$5000/year', duration: '1-2 years', scholarshipFees: '$1500/semester' },
  
  { value: 'pgd_logistics', label: 'PG Diploma in Logistics and Supply Chain', category: 'business', fees: '$3200/year', duration: '1 year', scholarshipFees: '$1500/semester' },
  { value: 'pgd_ir', label: 'PG Diploma in Industrial Relations and Labour', category: 'business', fees: '$3200/year', duration: '1 year', scholarshipFees: '$1500/semester' },
  { value: 'pgd_trade', label: 'PG Diploma in International Trade and Export', category: 'business', fees: '$3200/year', duration: '1 year', scholarshipFees: '$1500/semester' },
  { value: 'pgd_event', label: 'PG Diploma in Event Management', category: 'business', fees: '$3200/year', duration: '1 year', scholarshipFees: '$1500/semester' },
  { value: 'pgd_retail', label: 'PG Diploma in Retail Management', category: 'business', fees: '$3200/year', duration: '1 year', scholarshipFees: '$1500/semester' },
  { value: 'pgd_hospital', label: 'PG Diploma in Hospital Administration', category: 'business', fees: '$3200/year', duration: '1 year', scholarshipFees: '$1500/semester' },
  
  { value: 'phd_engineering', label: 'Ph.D. Engineering & Technology', category: 'engineering', fees: '$5000/year', duration: '3-5 years', scholarshipFees: '$2000/semester' },
  { value: 'phd_pharmacy', label: 'Ph.D. Pharmaceutical Sciences', category: 'medical', fees: '$4000/year', duration: '3-5 years', scholarshipFees: '$2000/semester' },
  { value: 'phd_management', label: 'Ph.D. Management Studies', category: 'business', fees: '$5000/year', duration: '3-5 years', scholarshipFees: '$1500/semester' },
];

// Detailed courses with full information
export const detailedCourses: DetailedCourse[] = [
  {
    id: 1,
    name: "B.Tech Computer Science & Engineering",
    category: "engineering",
    icon: Code,
    description: "A 4-year undergraduate program focusing on computer programming, algorithms, data structures, computer networks, and software engineering principles.",
    duration: "4 years",
    averageFees: "$3,000 per year",
    scholarshipFees: "$1,000 per semester",
    topUniversities: ["IIT Bombay", "IIT Delhi", "BITS Pilani", "NIT Trichy", "VIT Vellore"],
    careerProspects: ["Software Developer", "Systems Analyst", "Data Scientist", "Web Developer", "AI Engineer"],
    eligibility: "10+2 with Physics, Chemistry, and Mathematics with minimum 60%",
    skills: ["Programming", "Problem Solving", "Data Structures", "Algorithms", "Software Development"],
    featured: true,
  },
  {
    id: 2,
    name: "B.Tech Artificial Intelligence",
    category: "engineering",
    icon: CpuChip,
    description: "A specialized engineering program focusing on AI algorithms, machine learning, neural networks, and intelligent systems development.",
    duration: "4 years",
    averageFees: "$3,000 per year",
    scholarshipFees: "$1,200 per semester",
    topUniversities: ["IIT Bombay", "IIT Hyderabad", "IIIT Bangalore", "VIT Vellore", "Manipal Institute of Technology"],
    careerProspects: ["AI Engineer", "Machine Learning Specialist", "Data Scientist", "AI Research Associate", "Robotics Engineer"],
    eligibility: "10+2 with Physics, Chemistry, and Mathematics with minimum 65%",
    skills: ["Machine Learning", "Deep Learning", "Python", "Data Analysis", "Neural Networks"],
    featured: true,
  },
  {
    id: 3,
    name: "B.Tech Mechanical Engineering",
    category: "engineering",
    icon: Layers,
    description: "Deals with the design, analysis, manufacturing, and maintenance of mechanical systems including engines, machines, and thermal devices.",
    duration: "4 years",
    averageFees: "$3,000 per year",
    scholarshipFees: "$900 per semester",
    topUniversities: ["IIT Madras", "IIT Kharagpur", "BITS Pilani", "VIT Vellore", "Delhi Technological University"],
    careerProspects: ["Mechanical Engineer", "Product Designer", "Manufacturing Engineer", "CAD Specialist", "Project Manager"],
    eligibility: "10+2 with Physics, Chemistry, and Mathematics with minimum 60%",
    skills: ["CAD/CAM", "Thermodynamics", "Manufacturing Processes", "Fluid Mechanics", "Design Analysis"],
    featured: false,
  },
  {
    id: 4,
    name: "M.Tech Computer Science & Engineering",
    category: "engineering",
    icon: Database,
    description: "Advanced program focusing on specialized areas of computer science like AI, machine learning, data science, and computer networks.",
    duration: "2 years",
    averageFees: "$4,000 per year",
    scholarshipFees: "$1,250 per semester",
    topUniversities: ["IISc Bangalore", "IIT Bombay", "IIT Delhi", "IIT Madras", "IIT Kanpur"],
    careerProspects: ["Research Scientist", "Senior Software Engineer", "IT Architect", "Tech Lead", "University Professor"],
    eligibility: "B.Tech/B.E in Computer Science or related field with minimum 60%",
    skills: ["Advanced Algorithms", "Research Methodologies", "Specialized Programming", "System Design", "AI/ML"],
    featured: true,
  },
  {
    id: 5,
    name: "MBA (Master of Business Administration)",
    category: "business",
    icon: Briefcase,
    description: "A postgraduate program covering various aspects of business management including finance, marketing, human resources, and operations.",
    duration: "2 years",
    averageFees: "$3,200 per year",
    scholarshipFees: "$1,000 per semester",
    topUniversities: ["IIM Ahmedabad", "IIM Bangalore", "IIM Calcutta", "ISB Hyderabad", "XLRI Jamshedpur"],
    careerProspects: ["Business Manager", "Marketing Manager", "Financial Analyst", "Consultant", "Entrepreneur"],
    eligibility: "Bachelor's degree in any discipline with minimum 50% and valid entrance exam score",
    skills: ["Leadership", "Strategic Thinking", "Financial Analysis", "Marketing Strategy", "Operations Management"],
    featured: true,
  },
  {
    id: 6,
    name: "B.Pharmacy",
    category: "medical",
    icon: HeartPulse,
    description: "An undergraduate program focusing on pharmaceutical sciences, drug formulation, pharmacology, and medicinal chemistry.",
    duration: "4 years",
    averageFees: "$4,000 per year",
    scholarshipFees: "$1,250 per semester",
    topUniversities: ["NIPER Mohali", "Jamia Hamdard", "BHU Varanasi", "Manipal College of Pharmaceutical Sciences", "ICT Mumbai"],
    careerProspects: ["Pharmacist", "Drug Safety Associate", "Clinical Research Associate", "Regulatory Affairs Specialist", "Quality Control Analyst"],
    eligibility: "10+2 with Physics, Chemistry, and Biology/Mathematics with minimum 55%",
    skills: ["Pharmacology", "Pharmaceutical Chemistry", "Drug Formulation", "Patient Counseling", "Regulatory Knowledge"],
    featured: false,
  },
  {
    id: 7,
    name: "B.Tech Cyber Security",
    category: "engineering",
    icon: ShieldCheck,
    description: "Specialized program focusing on network security, ethical hacking, cryptography, digital forensics, and security architecture.",
    duration: "4 years",
    averageFees: "$3,000 per year",
    scholarshipFees: "$1,200 per semester",
    topUniversities: ["IIT Kanpur", "IIIT Hyderabad", "DIAT Pune", "Amity University", "SRM University"],
    careerProspects: ["Security Analyst", "Ethical Hacker", "Security Consultant", "Forensic Expert", "SOC Analyst"],
    eligibility: "10+2 with Physics, Chemistry, and Mathematics with minimum 60%",
    skills: ["Network Security", "Penetration Testing", "Cryptography", "Security Analysis", "Digital Forensics"],
    featured: true,
  },
  {
    id: 8,
    name: "B.Tech Internet of Things (IoT)",
    category: "engineering",
    icon: Wifi,
    description: "Cutting-edge program focusing on connected devices, embedded systems, sensor networks, and IoT architecture and protocols.",
    duration: "4 years",
    averageFees: "$3,000 per year",
    scholarshipFees: "$1,200 per semester",
    topUniversities: ["IIT Delhi", "IIIT Bangalore", "VIT Vellore", "MIT-ADT University", "SRM University"],
    careerProspects: ["IoT Solutions Architect", "Embedded Systems Engineer", "IoT Developer", "Smart System Designer", "IoT Security Specialist"],
    eligibility: "10+2 with Physics, Chemistry, and Mathematics with minimum 60%",
    skills: ["Embedded Programming", "Sensor Technology", "Network Protocols", "Cloud Computing", "Data Analytics"],
    featured: false,
  },
  {
    id: 9,
    name: "B.Tech Automobile Engineering",
    category: "engineering",
    icon: Car,
    description: "Specialized engineering program focusing on vehicle design, automotive systems, engine technology, and manufacturing.",
    duration: "4 years",
    averageFees: "$3,000 per year",
    scholarshipFees: "$900 per semester",
    topUniversities: ["IIT Delhi", "VIT Vellore", "SRM University", "Manipal Institute of Technology", "Delhi Technological University"],
    careerProspects: ["Automobile Engineer", "Vehicle Designer", "Production Engineer", "Quality Control Manager", "R&D Specialist"],
    eligibility: "10+2 with Physics, Chemistry, and Mathematics with minimum 60%",
    skills: ["Vehicle Design", "Automotive Systems", "Engine Technology", "CAD/CAM", "Manufacturing Processes"],
    featured: false,
  },
  {
    id: 10,
    name: "B.Tech Drone Technology",
    category: "engineering",
    icon: Cpu,
    description: "Cutting-edge program focusing on UAV design, flight dynamics, drone programming, navigation systems, and applications.",
    duration: "4 years",
    averageFees: "$3,000 per year",
    scholarshipFees: "$1,200 per semester",
    topUniversities: ["IIT Bombay", "IIT Madras", "Lovely Professional University", "VIT Vellore", "SRM University"],
    careerProspects: ["Drone Engineer", "UAV Designer", "Drone Programmer", "Aerial Mapping Specialist", "Drone Application Developer"],
    eligibility: "10+2 with Physics, Chemistry, and Mathematics with minimum 60%",
    skills: ["UAV Design", "Flight Dynamics", "Embedded Systems", "Image Processing", "Control Systems"],
    featured: true,
  },
  {
    id: 11,
    name: "B.Tech Aerospace Engineering",
    category: "engineering",
    icon: Atom,
    description: "Specialized program focusing on aircraft and spacecraft design, aerodynamics, propulsion systems, and aerospace structures.",
    duration: "4 years",
    averageFees: "$4,000 per year",
    scholarshipFees: "$1,200 per semester",
    topUniversities: ["IIT Bombay", "IIT Madras", "IIT Kanpur", "Indian Institute of Aeronautical Engineering", "PEC Chandigarh"],
    careerProspects: ["Aerospace Engineer", "Aircraft Designer", "Avionics Specialist", "Spacecraft Engineer", "Aerodynamics Analyst"],
    eligibility: "10+2 with Physics, Chemistry, and Mathematics with minimum 70%",
    skills: ["Aerodynamics", "Propulsion Systems", "Aerospace Structures", "Flight Mechanics", "Aircraft Design"],
    featured: true,
  },
  {
    id: 12,
    name: "M.Tech Renewable Energy Resources",
    category: "engineering",
    icon: Leaf,
    description: "Advanced program focusing on solar, wind, hydro, and other renewable energy technologies, sustainability, and energy management.",
    duration: "2 years",
    averageFees: "$4,000 per year",
    scholarshipFees: "$1,250 per semester",
    topUniversities: ["IIT Delhi", "IIT Bombay", "TERI School of Advanced Studies", "MNIT Jaipur", "NIT Trichy"],
    careerProspects: ["Renewable Energy Engineer", "Solar Energy Specialist", "Energy Consultant", "Sustainability Manager", "Wind Energy Analyst"],
    eligibility: "B.Tech/B.E in relevant engineering discipline with minimum 60%",
    skills: ["Solar Technology", "Wind Energy Systems", "Energy Storage", "Sustainable Design", "Power Systems"],
    featured: false,
  },
  {
    id: 13,
    name: "BSc Animation VFX and Game Art",
    category: "design",
    icon: Palette,
    description: "Creative program focusing on 2D/3D animation, visual effects, game design, character modeling, and digital storytelling.",
    duration: "3 years",
    averageFees: "$5,000 per year",
    scholarshipFees: "$1,200 per semester",
    topUniversities: ["National Institute of Design", "MAAC", "Arena Animation", "Whistling Woods International", "FX School"],
    careerProspects: ["3D Animator", "VFX Artist", "Game Designer", "Character Modeler", "Motion Graphics Artist"],
    eligibility: "10+2 in any stream with minimum 50% and portfolio/entrance test",
    skills: ["3D Modeling", "Animation Principles", "VFX Compositing", "Game Design", "Character Creation"],
    featured: true,
  },
  {
    id: 14,
    name: "MBA in Digital Marketing",
    category: "business",
    icon: Lightbulb,
    description: "Specialized MBA program focusing on digital marketing strategies, SEO, social media marketing, analytics, and online branding.",
    duration: "2 years",
    averageFees: "$3,200 per year",
    scholarshipFees: "$1,000 per semester",
    topUniversities: ["IIM Calcutta", "MICA Ahmedabad", "SPJIMR Mumbai", "Symbiosis Institute of Business Management", "IMT Ghaziabad"],
    careerProspects: ["Digital Marketing Manager", "SEO Specialist", "Social Media Strategist", "Content Marketing Manager", "Digital Brand Manager"],
    eligibility: "Bachelor's degree in any discipline with minimum 50% and valid entrance exam score",
    skills: ["Digital Strategy", "SEO/SEM", "Social Media Marketing", "Content Marketing", "Web Analytics"],
    featured: false,
  },
  {
    id: 15,
    name: "Ph.D. Management Studies",
    category: "business",
    icon: GraduationCap,
    description: "Research-based doctoral program focusing on advanced business theories, research methodologies, and specialized management disciplines.",
    duration: "3-5 years",
    averageFees: "$5,000 per year",
    scholarshipFees: "$1,500 per semester",
    topUniversities: ["IIM Ahmedabad", "IIM Bangalore", "IIT Delhi", "FMS Delhi", "XLRI Jamshedpur"],
    careerProspects: ["Professor", "Research Scientist", "Management Consultant", "Corporate Strategist", "Academic Dean"],
    eligibility: "Master's degree in Management or related field with minimum 60% and research aptitude",
    skills: ["Research Methodology", "Statistical Analysis", "Academic Writing", "Critical Thinking", "Specialized Knowledge"],
    featured: false,
  },
];